# Generated by Django 5.2.8 on 2025-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Polygon coordinates as array of [lat, lng] pairs', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Center point latitude (optional if polygon is provided)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Center point longitude (optional if polygon is provided)', max_digits=9, null=True),
        ),
    ]
