# Generated by Django 5.2.8 on 2025-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0002_zone_polygon_alter_zone_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', help_text='Type of zone: circle or polygon', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Center point latitude (required for circle zones)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Center point longitude (required for circle zones)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Polygon coordinates as array of [lat, lng] pairs (required for polygon zones)', null=True),
        ),
    ]
