# Generated by Django 5.2.8 on 2025-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0003_zone_zone_type_alter_zone_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email of the user who sent the SOS', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='Name of the user', max_length=255, null=True)),
                ('sos_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('lost', 'Lost Person'), ('danger', 'In Danger'), ('crowd', 'Crowd Emergency'), ('other', 'Other Emergency')], help_text='Type of emergency', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of emergency location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of emergency location', max_digits=9)),
                ('description', models.TextField(blank=True, help_text='Additional details about the emergency', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', help_text='Current status of the request', max_length=20)),
                ('assigned_team', models.CharField(blank=True, help_text='Team assigned to handle this request', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SOS Request',
                'verbose_name_plural': 'SOS Requests',
                'db_table': 'sos_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
