# Generated by Django 5.2.8 on 2025-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0004_sosrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('food', 'Food & Water'), ('restroom', 'Restrooms'), ('parking', 'Parking'), ('accommodation', 'Accommodation'), ('transport', 'Transport'), ('worship', 'Worship'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=50),
        ),
    ]
