# Generated by Django 5.2.8 on 2025-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0005_alter_amenity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email of the user who added this family member', max_length=254)),
                ('name', models.CharField(help_text='Name of the family member', max_length=255)),
                ('phone', models.CharField(help_text='Phone number of the family member', max_length=20)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('friend', 'Friend'), ('other', 'Other')], help_text='Relationship to the user', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Last known latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Last known longitude', max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='Last time location was updated', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'family_members',
                'ordering': ['-created_at'],
                'unique_together': {('user_email', 'phone')},
            },
        ),
    ]
