# Generated by Django 5.2.8 on 2025-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0006_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_email', models.EmailField(help_text='Email of the user who sent the invitation', max_length=254)),
                ('invitee_email', models.EmailField(help_text='Email of the user being invited', max_length=254)),
                ('token', models.CharField(help_text='Unique invitation token', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', help_text='Invitation status', max_length=20)),
                ('relationship', models.CharField(blank=True, help_text='Suggested relationship (optional)', max_length=20, null=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
            ],
            options={
                'verbose_name': 'Family Invitation',
                'verbose_name_plural': 'Family Invitations',
                'db_table': 'family_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
