# Generated by Django 5.2.8 on 2025-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0007_familyinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], help_text='Type of report: lost or found', max_length=20)),
                ('user_email', models.EmailField(help_text='Email of the user who created the report', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='Name of the reporter', max_length=255, null=True)),
                ('user_phone', models.CharField(blank=True, help_text='Phone number of the reporter', max_length=20, null=True)),
                ('person_name', models.CharField(help_text='Name of the lost/found person or item', max_length=255)),
                ('age', models.IntegerField(blank=True, help_text='Age of the person (if applicable)', null=True)),
                ('description', models.TextField(help_text='Description of the person/item')),
                ('location', models.CharField(help_text='Location where lost/found', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the location', max_digits=9, null=True)),
                ('photo_url', models.URLField(blank=True, help_text='URL of the photo (if uploaded)', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the report', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lost & Found Report',
                'verbose_name_plural': 'Lost & Found Reports',
                'db_table': 'lost_found',
                'ordering': ['-created_at'],
            },
        ),
    ]
