# Generated by Django 5.2.8 on 2026-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0008_lostfound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(help_text='Event description')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['event_date'],
            },
        ),
    ]
