# Generated by Django 5.2.8 on 2026-01-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/identifier for this SMTP configuration', max_length=255)),
                ('host', models.CharField(help_text='SMTP server host', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('username', models.CharField(help_text='SMTP username/email', max_length=255)),
                ('password', models.CharField(help_text='SMTP password', max_length=255)),
                ('from_email', models.EmailField(help_text="Default 'from' email address", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text="Default 'from' name", max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default SMTP configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
                'db_table': 'smtp_settings',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
