# Generated by Django 5.2.8 on 2026-01-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbh', '0010_smtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the geographic feature', max_length=255)),
                ('feature_type', models.CharField(choices=[('road', 'Road'), ('area', 'Area'), ('zone', 'Zone'), ('parking', 'Parking'), ('holding_area', 'Holding Area'), ('staging_area', 'Staging Area'), ('release_point', 'Release Point'), ('route', 'Route'), ('other', 'Other')], default='other', help_text='Type of feature', max_length=50)),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], help_text='Type of geometry', max_length=20)),
                ('kmz_file_name', models.CharField(help_text='Source KMZ file name', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Point latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Point longitude', max_digits=9, null=True)),
                ('coordinates', models.JSONField(blank=True, help_text='Line or polygon coordinates as array of [lat, lng] pairs', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geographic Feature',
                'verbose_name_plural': 'Geographic Features',
                'db_table': 'geographic_features',
                'ordering': ['feature_type', 'name'],
            },
        ),
    ]
